language: node_js
node_js:
  - "8"
script:
  - yarn lint
  - yarn build
cache: yarn
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  name: Dominik Moritz
  email: domoritz@gmail.com
  project-name: editor
  script:
    - yarn generate-example-images
  addons:
    apt:
      packages:
        - parallel
  on:
    branch: master
    tags: true

